# Nixpacks configuration for full-stack Node.js app (not SPA)
[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
CI = "true"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "curl"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
cmd = "node dist/index.js"