# Nixpacks configuration for full-stack Node.js app
[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"
CI = "true"
NPM_CONFIG_TIMEOUT = "600000"

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x", "curl", "postgresql"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm ci --timeout=600000",
  "npm cache verify"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "npm run build"
]

[phases.migrate]
dependsOn = ["build"]
cmds = [
  "npm run db:push || echo 'Migration will run at startup'"
]

[start]
cmd = "node dist/index.js"